### ISSUE TITLE
Epic: CUDA/GPU wishlist (inference methods)

### ISSUE THREAD

**Issue by johnlees** [mrc-ide/mcstate#122]
- [ ] Implement speculative computation in the pMCMC using pars_multi
- [ ] Implement delayed acceptance in the pMCMC
- [ ] Fully parallel version of SMC^2
